---
- name: Zone(s) should be added
  route53_zone:
    region: "{{ item.region | default(omit) }}"
    aws_access_key: "{{ item.access_key | default(omit) }}"
    aws_secret_key: "{{ item.secret_key | default(omit) }}"
    profile: "{{ item.boto_profile | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    vpc_id: "{{ item.vpc_id | default(omit) }}"
    vpc_region: "{{ item.vpc_region | default(omit) }}"
    zone: "{{ item.zone }}"
    state: present
    validate_certs: True
  with_items: "{{ route53_zones_to_add }}"
  tags:
    - route53
    - dns_zones

- name: Record(s) should be added/updated
  route53:
    region: "{{ item.0.region | default(omit) }}"
    aws_access_key: "{{ item.0.access_key | default(omit) }}"
    aws_secret_key: "{{ item.0.secret_key | default(omit) }}"
    profile: "{{ item.0.boto_profile | default(omit) }}"
    zone: "{{ item.0.zone }}"
    record: "{{ item.1.record }}"
    type: "{{ item.1.type }}"
    ttl: "{{ item.1.ttl | default(omit) }}"
    value: "{{ item.1.value }}"
    command: create
    wait: True
    alias: "{{ item.1.alias | default(omit) }}"
    alias_hosted_zone_id: "{{ item.1.alias_hosted_zone_id | default(omit) }}"
    overwrite: "{{ item.1.overwrite | default('True') }}"
    private_zone: "{{ item.0.private_zone | default(omit) }}"
    validate_certs: True
  with_subelements:
    - "{{ route53_records_to_add }}"
    - records
  tags:
    - route53
    - dns_records

- name: Record(s) should be removed
  route53:
    region: "{{ item.0.region | default(omit) }}"
    aws_access_key: "{{ item.0.access_key | default(omit) }}"
    aws_secret_key: "{{ item.0.secret_key | default(omit) }}"
    profile: "{{ item.0.boto_profile | default(omit) }}"
    zone: "{{ item.0.zone }}"
    record: "{{ item.1.record }}"
    type: "{{ item.1.type }}"
    ttl: "{{ item.1.ttl | default(omit) }}"
    value: "{{ item.1.value }}"
    alias: "{{ item.1.alias | default(omit) }}"
    alias_hosted_zone_id: "{{ item.1.alias_hosted_zone_id | default(omit) }}"
    command: delete
    wait: True
    private_zone: "{{ item.0.private_zone | default(omit) }}"
    validate_certs: True
  with_subelements:
    - "{{ route53_records_to_remove }}"
    - records
  tags:
    - route53
    - dns_records

- name: Zone(s) should be removed
  route53_zone:
    region: "{{ item.region | default(omit) }}"
    aws_access_key: "{{ item.access_key | default(omit) }}"
    aws_secret_key: "{{ item.secret_key | default(omit) }}"
    profile: "{{ item.boto_profile | default(omit) }}"
    vpc_id: "{{ item.vpc_id | default(omit) }}"
    vpc_region: "{{ item.vpc_region | default(omit) }}"
    zone: "{{ item.zone }}"
    state: absent
    validate_certs: True
  with_items: "{{ route53_zones_to_remove }}"
  tags:
    - route53
    - dns_zones
